version: '3'

vars:
  PLUGIN_NAME: Jellyfin.Plugin.DiscordNotifier
  TARGET_FRAMEWORK: net9.0
  DOCKER_CONTAINER: jellyfin

  BUILD_DIR: 'bin/Debug/{{.TARGET_FRAMEWORK}}'
  PLUGIN_DEST: '../library/data/plugins/configurations/{{.PLUGIN_NAME}}'

tasks:
  build:
    desc: Build, Deploy and Restart
    cmds:
      - dotnet build {{.PLUGIN_NAME}}.csproj -c Debug
      - rm -rf {{.PLUGIN_DEST}}
      - mkdir -p {{.PLUGIN_DEST}}
      - cp -f {{.BUILD_DIR}}/{{.PLUGIN_NAME}}.dll {{.PLUGIN_DEST}}/
      - cp -f {{.BUILD_DIR}}/{{.PLUGIN_NAME}}.xml {{.PLUGIN_DEST}}/
      - docker exec {{.DOCKER_CONTAINER}} sh -c "chown -R 911:911 /config/data/plugins/configurations/{{.PLUGIN_NAME}}"
      - docker restart {{.DOCKER_CONTAINER}}

  clean:
    desc: Remove plugin and restart
    cmds:
      - rm -rf bin obj
      - rm -rf {{.PLUGIN_DEST}}
      - docker restart {{.DOCKER_CONTAINER}}
